baseURL = 'https://gnome.network/'
languageCode = 'en-us'
title = 'Adelore Lessard'
theme = 'shell'
canonicalURL = 'https://gnome.network/'

[params]
  description = "AWS Cloud Architect & Technical Leader"
  author = "Adelore Lessard"

[params.shell]
  username = "user"
  hostname = "gnome.network"

[[params.navlinks]]
  url = "/"
  name = "about"
[[params.navlinks]]
  url = "/resume/"
  name = "resume"
[[params.navlinks]]
  url = "/posts/"
  name = "posts"
