baseURL = 'https://gnome.network/'
languageCode = 'en-us'
title = 'Adelore Lessard'
theme = 'hugo-theme-console'
canonicalURL = 'https://gnome.network/'

[params]
  description = "AWS Cloud Architect & Technical Leader"
  author = "Adelore Lessard"

[[params.navlinks]]
  url = "/"
  name = "About"
[[params.navlinks]]
  url = "/resume/"
  name = "Resume"
[[params.navlinks]]
  url = "/posts/"
  name = "Blog"
